ynot: add support for bash completions
- add to bashrc in install script

diff --git a/helpers/check-command-name-valid b/helpers/check-command-name-valid
--- a/helpers/check-command-name-valid
+++ b/helpers/check-command-name-valid
@@ -8,6 +8,6 @@ COMMAND="${1:?Usage: $(basename "$0") <command>}"
 # right now, only lowercase a-z and hyphens
 # this eliminates a lot of annoying edge cases and encourages consistency
 if [[ "$COMMAND" =~ [^a-z\-] ]]; then
-   echo "$COMMAND: invalid command; must contain only hyphens and the lowercase letters a-z" >&2
+   echo "$COMMAND: invalid name for command; must contain only hyphens and the lowercase letters a-z" >&2
    exit 1
 fi
diff --git a/helpers/install-ynot b/helpers/install-ynot
--- a/helpers/install-ynot
+++ b/helpers/install-ynot
@@ -36,6 +36,7 @@ fi
 YNOT_ROOT="${YNOT_ROOT:-$DEFAULT_YNOT_ROOT}"
 YNOT_SYMLINK="${YNOT_SYMLINK:-$DEFAULT_YNOT_SYMLINK}"
 YNOT_PATH="$YNOT_ROOT/ynot" # ynot itself
+YNOT_PREPARE_SESSION_SCRIPT="$YNOT_ROOT/runtime/prepare-bash-session" # script to set completions etc.
 
 echo
 echo "ynot install dir: '$YNOT_ROOT'"
@@ -62,7 +63,7 @@ fi
 echo
 echo Checking for dependencies...
 MISSING_DEPS="false"
-for REQD_CMD in basename chmod column cp echo env find flock git mv paste realpath rm xargs; do
+for REQD_CMD in basename chmod column cp echo env find flock git ln mv paste realpath rm xargs; do
     CMD_PATH="$(which "$REQD_CMD" || true)"
     if [ -z "$CMD_PATH" ]; then
         # you're probably on macOS IDK
@@ -121,14 +122,24 @@ echo
 echo "Symlinking '$YNOT_SYMLINK' -> '$YNOT_PATH'..."
 ln -s "$YNOT_PATH" "$YNOT_SYMLINK"
 
+echo
+echo "Loading ynot session state... (bash completions etc.)"
+. "$YNOT_PREPARE_SESSION_SCRIPT"  # FIXME: does this break if the user isn't running bash?
+
+echo
+echo "Adding session state load to ~/.bashrc..."
+echo                                      >> "~/.bashrc"
+echo "# ynot bash completion, etc..."     >> "~/.bashrc"
+echo ". \"$YNOT_PREPARE_SESSION_SCRIPT\"" >> "~/.bashrc"
+
 # check the installation
 echo
 echo "Testing that ynot is installed in the path..."
 WHICH_YNOT_AFTER="$(which ynot || true)"
 
 if [ -z "$WHICH_YNOT_AFTER" ]; then
-    echo "Warning: ynot installed but not found in path;" >&2
-    echo "Verify the ynot symlink is installed in your path, then try running 'ynot list'" >&2
+    echo "Warning: ynot symlinked from '$YNOT_SYMLINK' but not found in path;" >&2
+    echo "Verify the symlink is accessible from your path, then try running 'ynot list'" >&2
     exit 2
 fi
 
