align output of ren and ingest
- make it clear that the command has moved and can now be invoked with ynot

diff --git a/provided/ingest b/provided/ingest
--- a/provided/ingest
+++ b/provided/ingest
@@ -4,9 +4,9 @@
 set -euo pipefail
 
 CMD_SOURCE_PATH="${1:?Usage: $(basename "$0") <file-to-ingest>}"
-CMD_SOURCE_NAME="$(basename "$CMD_SOURCE_PATH")"
 
-CMD_TARGET_PATH="$YNOT_CUSTOM/$CMD_SOURCE_NAME"
+CMD_NAME="$(basename "$CMD_SOURCE_PATH")"
+CMD_TARGET_PATH="$YNOT_CUSTOM/$CMD_NAME"
 
 if [ ! -f "$CMD_SOURCE_PATH" ]; then
    echo "Error: '$CMD_SOURCE_PATH' is not a file" >&2
@@ -15,14 +15,14 @@ elif [ ! -x "$CMD_SOURCE_PATH" ]; then
     echo "Error: '$CMD_SOURCE_PATH' is not marked as an executable file" >&2
     exit 2
 elif [ -f "$CMD_TARGET_PATH" ]; then
-    echo "Error: '$CMD_SOURCE_NAME' is already the name of a custom command"
+    echo "Error: '$CMD_NAME' is already the name of a custom command"
     exit 11
-elif [ -f "$YNOT_PROVIDED/$CMD_SOURCE_NAME" ]; then
-    echo "Error: '$CMD_SOURCE_NAME' is already the name of a provided command" >&2
+elif [ -f "$YNOT_PROVIDED/$CMD_NAME" ]; then
+    echo "Error: '$CMD_NAME' is already the name of a provided command" >&2
     exit 12
 fi
 
 # this can't create a new naming conflict as that's checked above
 mv "$CMD_SOURCE_PATH" "$CMD_TARGET_PATH"
 
-echo "$CMD_SOURCE_PATH -> $CMD_TARGET_PATH"
+echo "$CMD_SOURCE_PATH -> 'ynot $CMD_NAME'"
